import '@/styles/globals.css'

import { Toaster } from 'sonner'

import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'

import { ScrollArea } from '@/components/ui/scroll-area'
import { cn } from '@/lib/utils'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          'size-full h-screen overflow-hidden bg-background font-sans antialiased',
          fontSans.variable
        )}
      >
        <ScrollArea className="size-full max-h-screen">
          <div className="flex size-full min-h-screen flex-col justify-between">
            <main className="size-full flex-1">{children}</main>
          </div>
        </ScrollArea>
        <Toaster richColors position="top-right" />
      </body>
    </html>
  )
}
